site_name: ReMed.io
repo_url: https://github.com/remed-io
repo_name: ReMed.io

theme:
  name: material
  language: pt-BR
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: light blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: light blue
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  font:
    text: Roboto3
    code: Fira Code
  favicon : assets/logo.svg
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - header.social
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/remed-io
      name: GitHub da Organização
nav:
  - Visão Geral: index.md
  - Projeto Antigo: projeto-antigo.md
  - Regras de Negócio: regra-negocio.md
  - Product Backlog: backlog.md
